### ISSUE TITLE
WB versus WBP

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [Allar/ue4-style-guide#1]
I suppose that `WBP_` should be selected as preferred, because the `BP` letters are included in all other blueprint-related things. Promoting `WBP_` prefix will lead to more consistent style, imho.

From section https://github.com/Allar/ue4-style-guide#124-blueprints- ,

| Asset type | Prefix |
| --- | --- |
| Blueprint | BP_ |
| Blueprint Function Library | BPFL_ |
| Blueprint Interface | BPI_ |
| Blueprint Macro Library | BPML_ |
| Widget Blueprint | WB_ or WBP_ |

and from https://github.com/Allar/ue4-style-guide#122-animations-

| Asset type | Prefix |
| --- | --- |
| Animation Blueprint | ABP_ |

**Comment by Allar** [comment]
If you submit this as a pull request I'll approve it, that way you can be listed as a contributor.

**Comment by ShepherdZA** [comment]
This is great dude! Order and consistency is awesome. Thanks for taking the time to do this:)
