### ISSUE TITLE
Add Tutorial Blueprint

### ISSUE THREAD

**Issue by jonathanallvin** [Allar/ue4-style-guide#13]
I want to add the Tutorial Blueprint Class, it thinks it should be Blueprint (BP_)

**Comment by Allar** [comment]
Should it be BPT_?

**Comment by jonathanallvin** [comment]
The class is called "Tutorial Blueprint" in the menus so I should be "TBP_"  if you follow the names of the class. I checked and nothing else is shorten "TBP"

**Comment by Allar** [comment]
Added TBP_ in 34abe9c

Issue still open until added to Linter.
