### ISSUE TITLE
Animation Sequence & Sound Wave prefixes in conflict

### ISSUE THREAD

**Issue by RicardoGuzmanVelasco** [Allar/ue4-style-guide#27]
Both assets have the same prefix, A_, and none of them has suffix. Is that intentional?

**Comment by Allar** [comment]
It is intentional, as animation assets are generally not stored alongside audio files in a game's content tree. That is not always the case however, but for the general rule, it is nice to keep acronyms short even if there is some re-use if they generally do not co-exist.
