### ISSUE TITLE
Update style guide plugin to UE4.20

### ISSUE THREAD

**Issue by kuletxcore** [Allar/ue4-style-guide#28]
Hello! I love this guide, but unfortunately, the plugin is not for sale nor updated for the latest engine version.

I would love a mass rename tool. Thank you!

**Comment by Allar** [comment]
Unfortunately Linter ceases to exist as we know it. I should really update this to reflect that.

**Comment by drichardson** [comment]
@Allar are you saying that all references to the linter should be removed?

**Comment by samgutentag** [comment]
just giving this a bump :)
