### ISSUE TITLE
Decal Material

### ISSUE THREAD

**Issue by andreihaidu** [Allar/ue4-style-guide#29]
Any ideas on how to name decal materials, new prefix, adding a suffix to the material?

https://docs.unrealengine.com/en-us/Resources/ContentExamples/Decals

**Comment by drichardson** [comment]
For my project, I'm using a suffix (M_Footstep_Decal).

**Comment by Allar** [comment]
Makes sense to me. I'd merge in a PR for this.

**Comment by lucasdlk** [comment]
So this should be closed, no ?
