### ISSUE TITLE
Linter v2 for 4.26?

### ISSUE THREAD

**Issue by miltoncandelero** [Allar/ue4-style-guide#52]
Will there be a linter for 4.26?
I am trying to start here and I saw that the linter is not available for 4.26

**Comment by Allar** [comment]
Sorry about this, fixed.

**Comment by Yunir** [comment]
[People](https://www.unrealengine.com/marketplace/en-US/product/linter-v2/questions) and I cannot install it on MacOS for UE 4.26**.2**. Can you please take a look?

Steps to reproduce:
1. Use MacOS
2. Use UE 4.26.2
3. Add plugin from the marketplace
4. Press button `Install` and select 4.26 version - nothing happens.
